### ISSUE TITLE
Provide dragging information via scoped slot.

### ISSUE THREAD

**Issue by mortyccp** [cameronhimself/vue-drag-drop#1]
It would be great if the `Drag` component provides a scoped slot with information about the item itself is `dragging` or not. Also, the `Drop` component can also provide a scoped slot for `hovering` which the the dragging item hover on top of itself.

Providing scoped slot in this way, we can have the slot to change its appearance in response to a dragging process in a better way.

**Comment by cameronhimself** [comment]
Thanks for the suggestion! This sounds like a good idea. I'll look into it.

**Comment by cameronhimself** [comment]
Implemented in 868a770bd7d7958be175ea84bf143ae23e909d4d.
