### ISSUE TITLE
Not working on Microsoft Edge

### ISSUE THREAD

**Issue by UlasenkaUladzislau** [cameronhimself/vue-drag-drop#11]
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

I have this error on drag start:
SCRIPT1168: element not found
vue-drag-drop.common.js (1,1)  

Then When I over Dropzone I have:
SCRIPT438: Object doesn't support property or method 'find'
vue-drag-drop.common.js (1,1)

**Comment by cameronhimself** [comment]
Thanks! Looks like I need some polyfills. I'll look into it.

**Comment by karuban88** [comment]
Any update on this one?

**Comment by cameronhimself** [comment]
Thanks for the nudge. Take a look at my answer for #17. A very similar issue affects Edge--while it allows more than `'text'`, it only seems to allow for standard mimetypes in the `type` param. It doesn't seem like this is solvable given the hacky way I have to handle the data transfer :disappointed: It puts this component in a pretty horrible state. I didn't realize when I wrote it that the browser support was so inconsistent.
