### ISSUE TITLE
drag and drop for same div

### ISSUE THREAD

**Issue by gerryats** [cameronhimself/vue-drag-drop#12]
Hi @cameronhimself 
I have a list of files and folders and I would like to drag and drop(move) files and folders to another folder. Can I achieve it with this component ?

**Comment by akubasa** [comment]
Dear @gerryats,
I am also using this lib for drag and drop functionality with files and folders. This lib is perfect for that. I am unsing it to implement the same logic as google drive does.

**Comment by cameronhimself** [comment]
This library is a very thin wrapper around the [standard drag and drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API). Pretty much anything you can do with it, you can do with this library, including handling files.

As mentioned in the docs, all events are fired with the native event as the second argument, and it contains a [`files` property](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/files) on the `dataTransfer` object that should have everything you need.

I'm going to close this; feel free to open additional issues if you have more specific questions :)
