### ISSUE TITLE
@drop event not working

### ISSUE THREAD

**Issue by ajeetku** [cameronhimself/vue-drag-drop#13]
Drop event is not calling associated function

**Comment by cameronhimself** [comment]
Do you have an example repo or a JSFiddle demonstrating the error?

**Comment by ajeetku** [comment]
According to your documentation transferData prop to send data in drop function, but its not working.
so plaese update your documentaion to use transfer-data to transfer data.

**Comment by cameronhimself** [comment]
All documentation and examples have been changed to use `kebab-case` in markup rather than `camelCase`.
