### ISSUE TITLE
[Vue.tip] warning thrown when using camel cased prop (transferData)

### ISSUE THREAD

**Issue by nateritter** [cameronhimself/vue-drag-drop#14]
I'd like to suggest a quick change to all documentation and demos.  Changing from `:transferData` to `:transfer-data` alleviates the `[Vue.tip]` console warning which is thrown because of the camel casing. Kebab casing is preferred and changing this does not impact the functionality from what I can see at all.

**Comment by cameronhimself** [comment]
Thanks, and sorry for the delayed response. This should all be sorted out now.
