### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by haexhub** [cameronhimself/vue-drag-drop#16]
Hi,
I really like your library and would like to use it with typescript. Could you provide a declaration file for this?
Would be great.

best regards
haex

**Comment by cameronhimself** [comment]
Do you have an example repo of a Vue component that uses TypeScript? I'm not sure how it works.

**Comment by kdepp** [comment]
Looks like something I can contribute

**Comment by cameronhimself** [comment]
Added in version 1.1.3.

**Comment by kdepp** [comment]
Awesome,  it will be great if you can publish v1.1.3 on npm soon.  @cameronhimself

**Comment by cameronhimself** [comment]
Whoops, thought I already had. It's published now @kdepp @haexhub
