### ISSUE TITLE
draggable not working IE

### ISSUE THREAD

**Issue by maha83port** [cameronhimself/vue-drag-drop#18]
Chrome & Mozilla working but draggable not working IE please find solution & reply

**Comment by cameronhimself** [comment]
Unfortunately this is a [known issue](https://github.com/cameronhimself/vue-drag-drop/issues/17) and I don't currently see any way around it, given the non-standard way IE handles drag data. I'm sorry :disappointed:

**Comment by cameronhimself** [comment]
1.0.0 has been released with IE/Edge support.
