### ISSUE TITLE
add dependency

### ISSUE THREAD

**Issue by andangrd** [cameronhimself/vue-drag-drop#2]
I think, you forgot to add `vue-drag-drop` dependencies on your demo code. 
anyway, it's cool man..thanks 👍

**Comment by cameronhimself** [comment]
Ha... easy boneheaded mistake to make when you're using a local link. Thanks for bringing it to my attention.

**Comment by cameronhimself** [comment]
Resolved: https://github.com/cameronhimself/vue-drag-drop-demo/commit/ca5921ebfeadd20f63a8c472b08ea9493f83f564
