### ISSUE TITLE
add click event

### ISSUE THREAD

**Issue by haexhub** [cameronhimself/vue-drag-drop#21]
hi, could you please add a normal click event?
<drag @click = 'fancy_method' ></drag> doesn't work.

**Comment by cameronhimself** [comment]
Use [`@click.native`](https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components):
```vue
<drag @click.native="fancy_method" />
```

**Comment by haexhub** [comment]
thank you ;)
