### ISSUE TITLE
Doesn't work on mobile devices

### ISSUE THREAD

**Issue by soylomass** [cameronhimself/vue-drag-drop#25]
Hi, is mobile support planned? Otherwise, is there an easy solution to add mobile support? There are touchstart/move/end events for mobile, but I don't see how could we compatibilize them with drag/drop events.

**Comment by cameronhimself** [comment]
Unfortunately, given the very poor support of the HTML Drag and Drop API across mobile devices, and this package's explicit goal of being a lightweight wrapper around the HTML Drag and Drop API, there are no foreseeable plans to improve mobile support. It's up to the mobile browser developers to improve support for the API.
