### ISSUE TITLE
make draggable field type as [Object, Boolean]

### ISSUE THREAD

**Issue by anzolo** [cameronhimself/vue-drag-drop#28]
i have to make drag and drop to jquery.fancytree. For proper work draggable attribute need to be something like 
```
{
connectToFancytree: true,
revert: true
}
```
But now your component apply only Boolean type of draggable. Can you fix this, please?

**Comment by cameronhimself** [comment]
I'm going to need more information. The only purpose of the `draggable` attribute is to indicate whether or not the item is draggable. If you need to pass it an object, you're misusing it. If you can give me some more details about your integration and maybe link to a relevant part of the fancytree documentation I can try to help you out. I don't know anything about fancytree or what you're trying to accomplish.

**Comment by anzolo** [comment]
thanx for answer. i already understand that i was wrong.
but for another people with same question i explain.
your vue component implement HTML 5 Drag and Drop API.
And i wanted use it with jquery tree component [http://wwwendt.de/tech/fancytree/demo/](url)
fancytree implement jquery drag and drop behavior [http://api.jqueryui.com/draggable/](url)\
it`s different methods of drag and drop implementation, and don`t make sense to mix one another.
