### ISSUE TITLE
Hello... great little component, but...

### ISSUE THREAD

**Issue by sean-atomized** [cameronhimself/vue-drag-drop#3]
I have multiple drop locations in a `v-for`.  Is there a way to provide what drop zone the item was dragged into and dropped?

Consider this:

`<div v-for="item in items"><drop>drop {{ item.name }} {{ item.id }}</drop></div>`

In the same page I have a couple draggable items:

`<drag :transferData="{ id: id }">drag</drag>`

Thanks a bunch!

**Comment by sean-atomized** [comment]
Sorry, I actually looked at your source and just found the emit.  Thanks for making a good and easy plugin for this.  All the others are nice, but for over kill for simple drag and drops.  Thanks again!

**Comment by liquidvisual** [comment]
Hi @sean-atomized, I'm actually looking for similar functionality - I'm trying to create a drag and drop inventory system with this component and Vuex. How did you go about returning the drop element?

**Comment by TAnas0** [comment]
From the README:

> If you need to pass additional arguments in your event listener, the preferred method is to use the ES6 spread operator with arguments:
>  ```<drag @drag="myListener('foo', ...arguments)">Drag Me</drag>```

Use this functionality to pass to your listener the `key` of the dropzone, or whatever it has an id.
This example might help: https://github.com/cameronhimself/vue-drag-drop-demo/blob/master/src/Groups.vue
