### ISSUE TITLE
Error in browser: process is not defined

### ISSUE THREAD

**Issue by riophae** [cameronhimself/vue-drag-drop#30]
My project was created with [vue-cli](https://github.com/vuejs/vue-cli). webpack was able to bundling vue-drag-drop. However, I got this error on browser side:

![sp180302_190024](https://user-images.githubusercontent.com/1289884/36896027-fd3ade4a-1e4b-11e8-8182-f0b23ed1d4f7.png)

Seems this is related to the building process of vue-drag-drop, not the component itself.

**Comment by riophae** [comment]
I have tried configuring vue-cli to inject the `process` object, but somehow it just won't work. Can you look into this?

**Comment by cameronhimself** [comment]
Can you make a repo with the minimal package.json to reproduce this error? It looks like something has gone wrong with your build process, but I don't know that I can help you debug without more details.

**Comment by riophae** [comment]
I have managed to fix my build process. Now it's working fine. Thanks!

**Comment by mislavlukac** [comment]
@riophae What was wrong with your build process? I'm experiencing the same issue.

**Comment by riophae** [comment]
@mislavlukac I modified my webpack config:
```json
{
  "node": {
    "process": true
  }
}
```
The documentation: https://webpack.js.org/configuration/node/#node-process

**Comment by mislavlukac** [comment]
@riophae Thanks a lot !
