### ISSUE TITLE
Nest Drag component within Drop Component

### ISSUE THREAD

**Issue by akinhwan** [cameronhimself/vue-drag-drop#31]
My use case is a ticker on a timeline. I would simple like to make the entire timeline a droppable component, and the ticker itself the handle which I can drag along a constrained horizontal axis. Is this possible?

**Comment by cameronhimself** [comment]
I don't think this is the right tool for that job. The drag and drop API doesn't allow for locking to an axis, as far as I know. Have you taken a look at the various [Vue slider components](https://github.com/vuejs/awesome-vue#slider)?

**Comment by akinhwan** [comment]
@cameronhimself ah I didn't think to use a slider component, I think this could definitely work. Thank you.

**Comment by cameronhimself** [comment]
👍
