### ISSUE TITLE
Is it possible to drag and drop elements in the same list ?

### ISSUE THREAD

**Issue by ChucKN0risK** [cameronhimself/vue-drag-drop#32]
Hi @cameronhimself ,

First, thanks a lot for making this project. It really fits my needs 🙏

Is it possible to drag and drop elements in the same list like Vue-Draggable ?

I tried to nest `<drag>` components inside a `<drop>` one but it didn't work 🤔

<img src="https://raw.githubusercontent.com/SortableJS/Vue.Draggable/master/example.gif">

**Comment by cameronhimself** [comment]
You mean reordering items within a list? It's possible, but a bit awkward. I think you'd need to have each list item turn into a `Drop` (or be overlaid with a `Drop`) when you start dragging another list item. Dropping the list item onto any of those new `Drop`s would reorder the list item above the `Drop`. I can put together a fiddle for you when I have a bit more time.

**Comment by cameronhimself** [comment]
[Something like this](https://jsfiddle.net/gpg4c046/33/)? Needs a bit more styling for a better user experience, but I think that's the basic functionality you're after.

**Comment by ChucKN0risK** [comment]
This is exactly what I was trying to do yes ;) Thanks a lot @cameronhimself 🙏

**Comment by cameronhimself** [comment]
👍
