### ISSUE TITLE
Is dragging multiple elements at once possible?

### ISSUE THREAD

**Issue by ChucKN0risK** [cameronhimself/vue-drag-drop#34]
Hi @cameronhimself I was wondering if draging multiple elements at once was possible?

For instance, the user would select several elements with `Cmd` + `click` and then drop them.

**Comment by cameronhimself** [comment]
There is nothing in the Drag And Drop API about that. That would be a custom implementation.

**Comment by ChucKN0risK** [comment]
Ok thanks ;)
