### ISSUE TITLE
IE 11 issues

### ISSUE THREAD

**Issue by kwispel** [cameronhimself/vue-drag-drop#35]
Dropping an object in IE11 causes an 'Unexpected call to method or property access.' error. It is apparently connected to the setData method which in IE expects 'text' as mime-type instead of text/x-vue-drag-drop-key. 

It is reproducible at https://cameronhimself.github.io/vue-drag-drop/ demo page.

**Comment by n3m3s7s** [comment]
This is an issue even in MS Edge; the only mime-type accepted in IE/Edge is 'text';
also in the 'emitEvent' event this code:

transfer.setData("" + _constants.smuggleKeyMimeType + this.id, this.id);

always raise an error in IE/Edge;

I've resolved with the following code:

this.$set(_stores.transferDataStore, this.id, this.transferData);
transfer.setData(_constants.mimeType, this.id);
if (navigator.userAgent.indexOf('Edge') >= 0){}else{
    transfer.setData("" + _constants.smuggleKeyMimeType + this.id, this.id);
}
this.dragging = !0;

another quirks with IE/Edge is that transfer.setDragImage is poor supported... thanks Microsoft -.-'

**Comment by cameronhimself** [comment]
This is a known issue with all version of IE and Edge. I have a fix for it in the [1.0.0 branch](https://github.com/cameronhimself/vue-drag-drop/pull/23).

**Comment by cameronhimself** [comment]
1.0.0 has been released.
