### ISSUE TITLE
Issue styling cursor during drag 

### ISSUE THREAD

**Issue by ChucKN0risK** [cameronhimself/vue-drag-drop#37]
Hi! I want to style the cursor the way I want during the drag operation.
Thanks to this answer on StackOverflow I set in my dragover handler the `dropEffect` to `move`.

I precise that the elements I'm dragging are both a dropzone and a drag element.

I don't want to the cursor like below on the first 'Buttons' dropzone. I want the cursor to be a pointer

![screen capture on 2018-04-04 at 15-22-24](https://user-images.githubusercontent.com/3913276/38310149-1785ff16-381c-11e8-889b-0a3d3346d6af.gif)

So on my `drag` component I set both of the following property:
```
<drag :effect-allowed="'move'" :drop-effect="'move'"></drag>
```

However when I log the drag event the `dataTransfer` object looks like this:
```
dataTransfer: {
    dropEffect: "none",
    effectAllowed: "uninitialized"
}
```

What I am doing wrong here ?

Thanks in advance ;)

**Comment by ChucKN0risK** [comment]
Well I managed to remove the "+" cursor.

Before: 
```
handleDrag(category, transferData, e) {
    this.draggedElement = e.target.parentNode;
    if (!this.draggedElement.classList.contains('is-dragged')) {
        this.draggedElement.classList.add('is-dragged');
    }
    this.dragIsOccurring = true;
},
```

After:
```
handleDrag(category, transferData, e) {
    this.draggedElement = e.target.parentNode;
    this.dragIsOccurring = true;
},
```

All I did was dealing with a CSS class that has no cursor style attached to it.

I don't understand why my cursor changed 🤔

**Comment by cameronhimself** [comment]
I'm really not sure what was going on here without a full code example. I'm going to go ahead and close this since it sounds like you solved your issue. Feel free to reopen if I've misunderstood.
