### ISSUE TITLE
Unable to make this work with another draggable component

### ISSUE THREAD

**Issue by demonmind** [cameronhimself/vue-drag-drop#4]
I have another component called vue.draggable wrapping the vue-drag-drop element.

When I move the element in this plugin the other drag is triggered. Has there been any scenarios using multiple drag and drop plugins at the same time. This is my html structure

```
<div class="list">
  <div class="elements" vue.draggable>
     <div class="element" vue-drag-drop></div>
     <div class="element" vue-drag-drop></div>
     <div class="element" vue-drag-drop></div>
     <div class="element" vue-drag-drop></div>
  </div>
  <div class="elements" vue.draggable>
     <div class="element" vue-drag-drop></div>
     <div class="element" vue-drag-drop></div>
     <div class="element" vue-drag-drop></div>
     <div class="element" vue-drag-drop></div>
  </div>
  <div class="elements" vue.draggable>
     <div class="element" vue-drag-drop></div>
     <div class="element" vue-drag-drop></div>
     <div class="element" vue-drag-drop></div>
     <div class="element" vue-drag-drop></div>
  </div>
  ........
</div>
```

`Elements` are draggable within the list, but i want each `element` too to be draggable from one list of `elements` to the other

**Comment by demonmind** [comment]
Nevermind i answered my own question. In case anyone else has the same issue, I fixed it by declaring an explicit handle for the drag from the other library.

**Comment by ty7466** [comment]
Can u provide an example for this? I’m in the exact same situation.
