### ISSUE TITLE
IE11 support?

### ISSUE THREAD

**Issue by MBammann** [cameronhimself/vue-drag-drop#40]
Hello Cameron,

I'd like to use your libray in a project that has to support IE11.
Sadly it seems not to work in IE11 because of issues with dataTransfer.setData.
Do you see any way to make this work?

Thanks
Michael

**Comment by cameronhimself** [comment]
The bad news is: this is a known issue, and there is no workaround.
The good news is: a fix is planned for the 1.0.0 release, which should be happening very soon!

**Comment by cameronhimself** [comment]
1.0.0 released with IE/Edge support.

**Comment by MBammann** [comment]
It's still not working in IE11... :-(
I'm getting an error as soon as I start dragging on the demo page...
![grafik](https://user-images.githubusercontent.com/13415267/41122484-fe101b2c-6a9b-11e8-8e00-f48f53e9a84b.png)
