### ISSUE TITLE
Is it possible to have several image slot?

### ISSUE THREAD

**Issue by ChucKN0risK** [cameronhimself/vue-drag-drop#41]
Hi 👋,

I have a child and a parent component. Both are draggable and have their own image slot defined. 

Currently, only the parent's slot appears during the drag even if I am dragging the child component.

How can I specify a slot for a parent and another one for a child?

```vue
<div id="app">
  <div class="list">
    <drop v-for="(item, i) in items" @drop="onDrop(...arguments, i)">
      <drag
        class="drag"
        :key="i"
        :transfer-data="{ fromIndex: i }"
      >
        {{ item.label }}
        <div slot="image">parent slot: {{ item.label }}</div>
        <drag class="drag-child">
          {{item.childItem}}
          <div slot="image">child slot: {{ item.childItem }}</div>
        </drag>
      </drag>
    </drop>
  </div>
</div>
```

```js
Vue.use(VueDragDrop);

const app = new Vue({
  el: '#app',
  data: {
    items: [
      {
      	label: 'One',
        childItem: 'A'
      },
      {
      	label: 'Two',
        childItem: 'B'
      },
      {
      	label: 'Three',
        childItem: 'C'
      },
      {
      	label: 'Four',
        childItem: 'D'
      },
      {
      	label: 'Five',
        childItem: 'E'
      },
    ],
  },
  methods: {
    onDrop({ fromIndex }, event, toIndex) {
      this.swapItems(toIndex, fromIndex);
    },
    swapItems(x, y) {
      const b = this.items[y];
      Vue.set(this.items, y, this.items[x]);
      Vue.set(this.items, x, b);
    },
  },
});
```

Here's the fiddle: https://jsfiddle.net/nv5820cz/12/

Thanks in advance!

**Comment by cameronhimself** [comment]
Hello again! Thanks for reporting all of these issues, it's very helpful. And thank you enormously for including a JSFiddle.

Take a look at issue #20, particularly my code solution, and also the nested drag component example on [the demo page](https://cameronhimself.github.io/vue-drag-drop/). The core problem appears to be that, when you have nested drag elements, the `dragstart` event gets propagated up to the topmost element that can respond to a `dragstart` event, and _that_ is the component that actually gets dragged--not the component that the cursor was over. So, what you're seeing is not just that the image slot is coming from the parent, but that the whole series of drag-related events is (I believe) occurring to the parent, not the child.

The solution, as mentioned in the linked issue, is to `stopPropagation` on the child's native `dragstart` event. Also note that in Firefox and possibly other browsers, a draggable element _must_ have transfer data set on it, or it won't be possible to initiate a drag. I [modified your fiddle](https://jsfiddle.net/nv5820cz/105/) to demonstrate the fix (note that the child drag text is white, so you won't see if you drag immediately over to the white background).

Now, that said,  if what you want is for the child's image slot to be the one that appears, but for the drag/drop events to actually occur on the parent, that is simply not possible with this library. You _can_ spoof it, however, with creative use of the image slot.

**Comment by ChucKN0risK** [comment]
Well I found the error. The parent slot was selected because when I dragged my child element the dragevent bubbles to the parent. To prevent the event from bubbling to the parent all I had to do was adding `e.stopPropagation()` at the dragStart event on the child element.

Updated fiddle: https://jsfiddle.net/m0v41679/

**Comment by cameronhimself** [comment]
Oh, just a quick note. I'm considering dropping the automatic "hide" styling of the image slot for version 1. Currently, the content in the image slot gets automatically positioned off-screen so you can have drag HTML without it being visible when you're not dragging, but it's really hacky and browser support is inconsistent (it doesn't work at all in Safari, I seriously doubt it works in IE/Edge, and I think older versions of Chrome and FF are spotty). I'm uncomfortable having a feature in 1.0 that has such bad browser support.

I'm curious what you think of this change, since you seem to be using the library heavily. If the flimsy browser support isn't a problem for you, you could still easily do the hiding yourself by adding `position: fixed; top: -1000` to your top-level image slot element.

**Comment by ChucKN0risK** [comment]
So you're suggesting we just add `position: fixed; top: -1000px;` or something else to hide the image slot by ourselves? I wouldn't mind as long as you precise it in your documentation ;)

I think many people have their own way of hiding DOM elements wether it's by using utility classes or something else. I would personally use the last one described in this post: [https://snook.ca/archives/html_and_css/hiding-content-for-accessibility](https://snook.ca/archives/html_and_css/hiding-content-for-accessibility).
