### ISSUE TITLE
Nested droppable is not supported or in documentation

### ISSUE THREAD

**Issue by guitartsword** [cameronhimself/vue-drag-drop#42]
It will be nice to for this library to support the greedy option (as a prop?) as in jqueryUI that lets that makes possible drops inside nested drops without calling the drop of the parent.
http://api.jqueryui.com/droppable/#option-greedy

Expected
http://jsfiddle.net/Twisty/pd3pur85/

vue-drag-drop
https://jsfiddle.net/hvvaadk9/365/

**Comment by cameronhimself** [comment]
You just need to `stopPropagation` on the child's native drop event. [Modified fiddle](https://jsfiddle.net/hvvaadk9/366/). I'll add an example to the demo page :)

**Comment by cameronhimself** [comment]
https://github.com/cameronhimself/vue-drag-drop-demo/issues/5

**Comment by guitartsword** [comment]
thanks, really what i needed.
Where could I find this events documentation?
