### ISSUE TITLE
Update Minimal JS Fiddle to support Firefox

### ISSUE THREAD

**Issue by ChucKN0risK** [cameronhimself/vue-drag-drop#44]
I recently noticed [your minimal JSFiddle](https://jsfiddle.net/cameronhimself/hvvaadk9/) was not working anymore on Firefox. 

After [some research](http://mereskin.github.io/dnd/) I found that Firefox requires adding the draggable attribute,  **plus the ondragstart global event handler containing the set up of the data transfer object**.

**Old JSFiddle:**
```vue
<div id="app">
  <drag class="drag" :transfer-data="{ draggable }">{{ draggable }}</drag>
  <drop class="drop" @drop="handleDrop">Dropzone</drop>
</div>
``` 
```js
var demo = new Vue({
  el: '#app',
  data: () => ({ draggable: 'Drag Me'}),
  methods: {
    handleDrop(data, event) {
      alert(`You dropped with data: ${JSON.stringify(data)}`);
    },
  },
});
```

**New JSFiddle:**
```vue
<div id="app">
  <drag
    class="drag"
    :transfer-data="{ draggable }"
    @dragstart="handleDragstart"
   >
     {{ draggable }}
   </drag>
  <drop
    class="drop"
    @drop="handleDrop"
  >
    Dropzone
  </drop>
</div>

```

```js
var demo = new Vue({
  el: '#app',
  data: () => ({ draggable: 'Drag Me'}),
  methods: {
    handleDragstart(data, event) {
    	event.dataTransfer.setData('text/plain', data);
    },
    handleDrop(data, event) {
      alert(`You dropped with data: ${JSON.stringify(data)}`);
    }
  },
});
```

I wanted to update the JSFiddle link and do a pull request but I think it's simpler if you just update your JSFiddle ;)

**Comment by cameronhimself** [comment]
This is actually a regression introduced by the 1.0.0 update. It's resolved by e5458bfc107ce8e7cfeb2d0f76d0ed268f15a75b. Thanks!
