### ISSUE TITLE
Top offset is not enough to push drag html off screen

### ISSUE THREAD

**Issue by andrewhl** [cameronhimself/vue-drag-drop#48]
For some reason, with 

```javascript
          :image-x-offset="100"
          :image-y-offset="100"
```

the 'hidden' html image isn't being offset enough, and appears on the screen. This might be a quirk of my HTML, but I was wondering if you could increase the offset from -1000px to -2000px, or provide a prop to allow us to set any value we want.

Happy to submit a PR for this.

![screen shot 2018-06-10 at 09 42 35](https://user-images.githubusercontent.com/1120082/41202120-c4d70c6e-6c92-11e8-8829-3bc9fc7c6298.png)

**Comment by andrewhl** [comment]
PR submitted.

**Comment by cameronhimself** [comment]
Closing this based on PR comments.
