### ISSUE TITLE
Flag for draggable on/off

### ISSUE THREAD

**Issue by sean-atomized** [cameronhimself/vue-drag-drop#5]
What's the possibility of adding a prop that turns draggable true/false in the base drag component?

**Comment by cameronhimself** [comment]
Sure, I'm going to push a new version this weekend and I'll take a look at rolling that in.

**Comment by cameronhimself** [comment]
New version delayed by illness :mask:. Should be coming during the week.

**Comment by cameronhimself** [comment]
59ff3bd20dc4728cd2325a26dc700ca13dad6506
