### ISSUE TITLE
Drag-drop doesn't transfer data from object in Edge

### ISSUE THREAD

**Issue by Frederik112** [cameronhimself/vue-drag-drop#51]
When dragging an element to a droppable object, it hits all the events, but the dropped object is "undefined". 

It works fine in firefox and chrome, but not in Edge. 

Your live demo does the same thing in Edge, so I'm wondering if there's any fix coming?

![image](https://user-images.githubusercontent.com/11376028/41227997-1b76c818-6d77-11e8-804f-42eefd257338.png)

**Comment by cameronhimself** [comment]
Thanks, I'm looking into it.

**Comment by underdoeg** [comment]
I have something similar. But I dont know if it is related to the same issue. 

When I run the minimal example, everything works fine in firefox. But after integrating it into my own application. the transfer data is undefined. But the same code works in chrome just as expected.

I have installed the library with yarn and it is supposed to be version 1.1.0.

**Comment by cameronhimself** [comment]
This was a regression introduced by 1.1.0. [Resolved](https://github.com/cameronhimself/vue-drag-drop/commit/e5bf532e6b02303132ce5941edff1d092e175971) in version 1.1.1 (already published to NPM) by passing a string rather than an object to `setData`.

**Comment by underdoeg** [comment]
Thanks. I have just updated but still get an undefined in firefox?

**Comment by cameronhimself** [comment]
I can't reproduce either issue in Firefox. Are you sure you're not dealing with an old cached version?

**Comment by cameronhimself** [comment]
[This fiddle](https://jsfiddle.net/zh8kdgen/2/) is using the current version (1.1.1) and it's both running a `dragstart` handler (logging 'foo') and alerting with the correct transfer data in the current version of Firefox.

**Comment by underdoeg** [comment]
strange. the fiddle works for me as well. But within the project it does not. I did reinstall the dependency and the package.json in node_modules/vue-vue-drag-drop says it is 1.1.1. I also opened in firefox beta to eliminate potential caching issues but no dice...

This is the relevant code and it is actually very simple.

```
<el-col :xs="24" :sm="6" :md="4" :xl="4" :span="3">
		<drag :transfer-data="video" @dragstart="handleDragstart">
			<el-card class="videoCard" @mouseover.native="hover" @mouseleave.native="unhover">
				<div class="preview" style="text-align: center">
					<div v-if="!video.preview" class="not-available">{{ $t("message.previewNotAvailable") }}</div>
					<img v-else-if="video.preview !== ''"
						 :src="animatedPreview && video.previewGif ? video.previewGif : video.preview"/>
				</div>
				<div class="description">
					<span class="title">{{video.name}}</span><br/>
					<time class="date">{{$d(new Date(video.created), 'long')}}</time>
					<br/>
					<span class="duration">{{formatSeconds(video.duration)}}</span>
				</div>
			</el-card>
		</drag>
	</el-col>
```

```
<grid-layout>
			<grid-item v-for="item in layout"
					   :x="item.x"
					   :y="item.y"
					   :w="item.w"
					   :h="item.h"
					   :i="item.i">
				<drop @drop="onMediaDrop">
				{{item.i}}
				</drop>
			</grid-item>
		</grid-layout>
```

**Comment by underdoeg** [comment]
observation: with the dragenter listener, I get the correct data.

**Comment by cameronhimself** [comment]
I've attempted to reproduce the issue working from the code provided, but no luck. It's difficult, because it's incomplete, so I have to make a lot of guesses about what else is going on. If you can make a JSFiddle that reproduces the issue, or even a minimal repo, it would be an enormous help.

**Comment by underdoeg** [comment]
I can try tomorrow. its quite a lot of code with an api in the background. But maybe I'll manage to distil the important parts into a working fiddle. i'll keep you posted

**Comment by underdoeg** [comment]
but I do suspect some libraries clashing or something. because sometimes the drag and drop does not work at all on chrome. (no drop or accept events) strange enough multiple reloads fixes the issue...

**Comment by underdoeg** [comment]
Ok, I was able to locate the error. https://jsfiddle.net/zqn4jv3s/

The problem is that I have a router-link as a parent to the draggable.
