### ISSUE TITLE
Build fails when using this plugin in a Rollup project

### ISSUE THREAD

**Issue by izziaraffaele** [cameronhimself/vue-drag-drop#52]
Importing this plugin in a Rollup project results in an error saying:

```
'vue-drag-drop' is imported by XXX, but could not be resolved – treating it as an external dependency
No name was provided for external module 'vue-drag-drop' in options.globals – guessing 'VueDragDrop'
```

**Comment by cameronhimself** [comment]
This should be resolved with version 1.1.2. However, until I fix my build process to have better support for Rollup, you'll need to use the default import in your project rather than importing `Drag` and `Drop` separately. Like this:

```javascript
import Vue from 'vue';
import VueDragDrop from 'vue-drag-drop';

Vue.use(VueDragDrop);
```
