### ISSUE TITLE
Basic List Support Broken in IE

### ISSUE THREAD

**Issue by shortstuffsushi** [cameronhimself/vue-drag-drop#53]
I thought maybe this was due to something about my more complicated project, but it seems that the "Basic List Support" example [here](https://cameronhimself.github.io/vue-drag-drop/) doesn't work in IE. Elements aren't properly dragged between the elements.

The issue here is that [you're using](https://github.com/cameronhimself/vue-drag-drop-demo/blob/a58c3fbf87da3243328785b08270684baf4bfe02/src/Lists.vue#L9) the new object property defining syntax, which IE doesn't support.

If you change the code from `transfer-data="{ item, list, example: 'lists' }` to `transfer-data="{ item: item, list: list, example: 'lists' }` it should work I believe.

**Comment by cameronhimself** [comment]
Thanks! [Resolved](https://github.com/cameronhimself/vue-drag-drop-demo/commit/84916702241b2dd8cf57baf11bb1db578514ab36).
