### ISSUE TITLE
question about dragging and dropping from the same element

### ISSUE THREAD

**Issue by yanfali** [cameronhimself/vue-drag-drop#55]
Is it possible to have an element be both a draggable and a droppable? If so how? can I simply  nest them? I have some items that are drop targets but can be dragged between each other to swap them.

Thanks in advance.

**Comment by cameronhimself** [comment]
Yup, you can [nest them](https://jsfiddle.net/cameronhimself/p7tb9sde/). Doesn't take anything special.
