### ISSUE TITLE
Disable draggable for some part of div.

### ISSUE THREAD

**Issue by ayhanyunt12** [cameronhimself/vue-drag-drop#64]
Hello,
I have two div between drag elements, I want to disable draggable for one div and active for another div, is it possible?

**Comment by cameronhimself** [comment]
Do you have an example I can look at? I don't think I understand what you're trying to accomplish. Something like [this](https://jsfiddle.net/6koayzd3/12/)?

**Comment by cameronhimself** [comment]
Feel free to reopen if you need more help.
