### ISSUE TITLE
Broken dependency on eslint-plugin-react? Or a ESLint config problem?

### ISSUE THREAD

**Issue by szalapski** [cameronhimself/vue-drag-drop#66]
Tried to install and use vue-drag-drop for the first time.  Installation seemed to work, but on my first build, I get the following (with paths redacted).  Any suggestions on how to troubleshoot?  Why would we depend on something "...react" at all?  

I tried installing eslint-plugin-react, but it didn't help.

ERROR in ../node_modules/vue-drag-drop/dist/vue-drag-drop.common.js
      Module build failed (from ./node_modules/eslint-loader/index.js):
      Error: Failed to load plugin react: Cannot find module 'eslint-plugin-react'
         at Function.Module._resolveFilename 
          at Function.resolve 
          at Plugins.load 
          at Array.forEach 
          at Plugins.loadAll 
          at loadFromDisk 
          at Object.load 
          at Config.getPersonalConfig 
          at Config.getLocalConfigHierarchy 
          at Config.getConfigHierarchy 
          at Config.getConfigVector 
          at Config.getConfig 
          at processText 
          at CLIEngine.executeOnText 
          at lint 
          at transform 
	at (my app...)

**Comment by szalapski** [comment]
I tried an npm update to be sure, but it didn't help.  Could it be a conflict with the version of eslint I already have installed?

**Comment by szalapski** [comment]
Turns out there was a .eslintrc file in my home directory that I never put there.  Did this installation put it there?

I got rid of it, thus getting past the error, but then I get 280 ESLint errors, presumably because my ESLint is mistakenly linting the vue-drag-drop code.  Why?

**Comment by szalapski** [comment]
Turns out I had the wrong syntax: at the top level, I can write `async function foo() {...}` but inside a class I might write instead `async foo(.) {...}` without a `function` keyword.

**Comment by szalapski** [comment]
Sorry to have mistakenly closed this issue; I am still having this issue.  Any idea why my ESLint is  linting the vue-drag-drop code by default?

**Comment by szalapski** [comment]
Any thoughts?

**Comment by cameronhimself** [comment]
This isn't something I can really help debug with the info provided, and I strongly suspect it's not directly related to this package in any case. That said, if you'd like to put together a [repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff#how-to-create-a-minimal-reproduction) I'll take a look and try to help you out.

Given that this is a month old, I'm going to close. Feel free to reopen if the problem still exists and you can put a repro up.
