### ISSUE TITLE
Drop target when it contains complex DOM

### ISSUE THREAD

**Issue by pjfitzgibbons** [cameronhimself/vue-drag-drop#69]
Here's a jsfilddle
https://jsfiddle.net/pjfitzgibbons/uo4sx1v2/6/

The `<drag>` is on a bootstrap "row", each with multiple "col" columns.
The `<drop>` is around the grid, containing all <drop>'s.

When `@drop` is called, the target is always the exact "col" element under the cursor.

Is there a way to limit the `@drop` to only the "row" div, it's parent ?

Thanks,
Peter Fitzgibbons

**Comment by cameronhimself** [comment]
Use `event.currentTarget`, not `event.target`: https://jsfiddle.net/3evacryL/1/

https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget
