### ISSUE TITLE
Get the dropped zone Element

### ISSUE THREAD

**Issue by NabilLahssine** [cameronhimself/vue-drag-drop#7]
Hi,

I have multiple columns (dropped zones) where I can drop some elements. I want to know if there is any way to get the column tag once I dragOver or I drop the element to it. So I can make some CSS and other changes.

(I hope this was clear enough)

Thank you

**Comment by cameronhimself** [comment]
It's not a good idea in Vue to get the element itself for the purposes of modifying the style. This use-case is covered in the [examples](https://cameronhimself.github.io/vue-drag-drop/) (look for "Custom drag-over styling"). The source code for that particular example is [here](https://github.com/cameronhimself/vue-drag-drop-demo/blob/master/src/Styling.vue). Does that help?

**Comment by demonmind** [comment]
This looks like the same question i had. Look at Issue #8 in closed

**Comment by NabilLahssine** [comment]
@cameronhimself Thank you so much for that.

**Comment by cameronhimself** [comment]
Do you have an example?

**Comment by cameronhimself** [comment]
I'm going to go ahead and close this; feel free to reopen if you have additional details.

**Comment by liquidvisual** [comment]
For anyone who might stumble onto this. I managed to find the drop object through the following pen:

https://codepen.io/liquidvisual/pen/zjgVzz?editors=1011

```
 <drop v-for="item in dropzones"
         @drop="handleDrop($event, item)"> // $event is the drag obj, item is the drop obj
      Dropzone
  </drop>
```

If you're looking for the element, you could just use event.target on the drop method or use $refs.
