### ISSUE TITLE
Hover class not being set correctly

### ISSUE THREAD

**Issue by demonmind** [cameronhimself/vue-drag-drop#8]
I have a grid and each cell is a droppable container.

What i want to achieve is drag a div over a cell and while over the cell changes the background, like in the example shown.

Problem with that that all cells take that class over when i start dragging.
How can i solve this situation.

**Comment by cameronhimself** [comment]
[Does this help](https://jsfiddle.net/cameronhimself/966w9npp/1/)? Each dropzone needs to have its own hover state in your application.

**Comment by demonmind** [comment]
Adapting my data to your fiddle and trying. Thanks and will close if i solve the issue.

**Comment by cameronhimself** [comment]
Cool. Just so you know, for reasons having to do with the drag and drop API being quite dumb, the dragenter and dragleave events can be unreliable if you have HTML elements stacked inside your dropzone. If that's the case, I might consider using `Drop`'s default slot scope, [like this](https://jsfiddle.net/cameronhimself/su56m58o/). See the [Vue docs](https://vuejs.org/v2/guide/components.html#Scoped-Slots) about scoped slots.

Under the hood, the slot scope is only populated when a dragover is happening, which is tricky to check for manually, so it's a useful workaround. I should probably make it more visible.

**Comment by demonmind** [comment]
Second Option was more difficult in my case with the data structure i have, but i did adapt the data to your first solution and it works now. Thank a lot!
