### ISSUE TITLE
draggable not working correct

### ISSUE THREAD

**Issue by akubasa** [cameronhimself/vue-drag-drop#9]
When :draggable="false" and I try to drag an element at first time it is unable to be dragged (which is ok), if I try to drag the same element again, it is able to be dragged, while draggable is still set to false

**Comment by cameronhimself** [comment]
I'm not able to reproduce this. Do you have fiddle I can look at?

**Comment by cameronhimself** [comment]
Are there any other details you can give me?

**Comment by akubasa** [comment]
I have :draggable="false" prop set on the drag element.
I am using drag element with image slot.

When draggable is set to false you should not be able to see the image slot when draging the element, this is working 2 times e.g. but the third time you are able to drag it.

Sometimes :draggable is not working at all, sometimes 3rd or 2nd time.

**Comment by cameronhimself** [comment]
I have still been unable to reproduce this issue. If @cincarnato or @akubasa would like to provide a minimal reproduction or JSFiddle I'd be happy to take a look.

**Comment by cincarnato** [comment]
I realized that this happens when you select text inside and outside the draggable component

**Comment by davidlandais** [comment]
@cameronhimself I confirm, it happen when you select the text.
- Select the text.
- Release your mouse click.
- Click one time on the text selected then try to drag it.

I'm on OS X 10.13 under Chrome 70.

**Comment by cameronhimself** [comment]
Oh, that explains it. That's not a bug with this package, though. Your OS is allowing you to drag text when you select it, and there's nothing I can do about that. I suggest using the [`user-select` CSS rule](https://stackoverflow.com/a/4407335/1085970) to disable text selection if it isn't desired.

**Comment by gmw-web** [comment]
Came across this as I have the same issue. I'm working with a custom drag handle though. 

A codeSandbox of my situation where the problem can be experienced is available here:
https://codesandbox.io/s/4x6jyy8r7x

My drag handle works as expected, but after selecting text in the dragzone this text can be dragged to the dropzone (even though `draggable=false` for the element). 
On the drop the actual `transfer-data` is transfered, but I would have hoped this to be `undefined` or `null`.

@cameronhimself , is the 'transfer-data' something that can be cleared in this case (be empty when draggable=false)? In that case at least we can handle these edge cases on the drop. 
In my case it would be really inconvenient if I had to set the `user-select` CSS rule for my drag element.
